name: CI

on:
    push:
        branches:
            - main
    pull_request:

env:
    CARGO_TERM_COLOR: always

jobs:
    check:
        name: Check
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: dtolnay/rust-toolchain@stable
            - run: cargo check --all-features --all-targets
            - run: cargo fmt --all -- --check
            - run: cargo clippy --all-features --all-targets -- -D warnings

    run:
        name: Run
        needs: [check]
        strategy:
          matrix:
            os: [ubuntu-latest, windows-latest, macos-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v4
            - uses: dtolnay/rust-toolchain@stable
            - run: cargo run
            - run: cargo run --release
